/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReservationCheckRouteImport } from './routes/reservation-check'
import { Route as ConcertsRouteImport } from './routes/concerts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReservationLoginCodeRouteImport } from './routes/reservation.$loginCode'
import { Route as ConcertsConcertIdRouteImport } from './routes/concerts.$concertId'

const ReservationCheckRoute = ReservationCheckRouteImport.update({
  id: '/reservation-check',
  path: '/reservation-check',
  getParentRoute: () => rootRouteImport,
} as any)
const ConcertsRoute = ConcertsRouteImport.update({
  id: '/concerts',
  path: '/concerts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationLoginCodeRoute = ReservationLoginCodeRouteImport.update({
  id: '/reservation/$loginCode',
  path: '/reservation/$loginCode',
  getParentRoute: () => rootRouteImport,
} as any)
const ConcertsConcertIdRoute = ConcertsConcertIdRouteImport.update({
  id: '/$concertId',
  path: '/$concertId',
  getParentRoute: () => ConcertsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/concerts': typeof ConcertsRouteWithChildren
  '/reservation-check': typeof ReservationCheckRoute
  '/concerts/$concertId': typeof ConcertsConcertIdRoute
  '/reservation/$loginCode': typeof ReservationLoginCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/concerts': typeof ConcertsRouteWithChildren
  '/reservation-check': typeof ReservationCheckRoute
  '/concerts/$concertId': typeof ConcertsConcertIdRoute
  '/reservation/$loginCode': typeof ReservationLoginCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/concerts': typeof ConcertsRouteWithChildren
  '/reservation-check': typeof ReservationCheckRoute
  '/concerts/$concertId': typeof ConcertsConcertIdRoute
  '/reservation/$loginCode': typeof ReservationLoginCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/concerts'
    | '/reservation-check'
    | '/concerts/$concertId'
    | '/reservation/$loginCode'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/concerts'
    | '/reservation-check'
    | '/concerts/$concertId'
    | '/reservation/$loginCode'
  id:
    | '__root__'
    | '/'
    | '/concerts'
    | '/reservation-check'
    | '/concerts/$concertId'
    | '/reservation/$loginCode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConcertsRoute: typeof ConcertsRouteWithChildren
  ReservationCheckRoute: typeof ReservationCheckRoute
  ReservationLoginCodeRoute: typeof ReservationLoginCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reservation-check': {
      id: '/reservation-check'
      path: '/reservation-check'
      fullPath: '/reservation-check'
      preLoaderRoute: typeof ReservationCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concerts': {
      id: '/concerts'
      path: '/concerts'
      fullPath: '/concerts'
      preLoaderRoute: typeof ConcertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservation/$loginCode': {
      id: '/reservation/$loginCode'
      path: '/reservation/$loginCode'
      fullPath: '/reservation/$loginCode'
      preLoaderRoute: typeof ReservationLoginCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concerts/$concertId': {
      id: '/concerts/$concertId'
      path: '/$concertId'
      fullPath: '/concerts/$concertId'
      preLoaderRoute: typeof ConcertsConcertIdRouteImport
      parentRoute: typeof ConcertsRoute
    }
  }
}

interface ConcertsRouteChildren {
  ConcertsConcertIdRoute: typeof ConcertsConcertIdRoute
}

const ConcertsRouteChildren: ConcertsRouteChildren = {
  ConcertsConcertIdRoute: ConcertsConcertIdRoute,
}

const ConcertsRouteWithChildren = ConcertsRoute._addFileChildren(
  ConcertsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConcertsRoute: ConcertsRouteWithChildren,
  ReservationCheckRoute: ReservationCheckRoute,
  ReservationLoginCodeRoute: ReservationLoginCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
